# Generated by Django 3.2.8 on 2022-07-18 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_auto_20220718_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_loc', models.CharField(default='Auccun', max_length=50, null=True)),
                ('dt_demande', models.DateField(default=datetime.date.today, null=True, verbose_name='Date')),
                ('dure', models.CharField(default='0', max_length=10, null=True)),
                ('destination', models.CharField(default='Auccun', max_length=100, null=True)),
                ('motif', models.CharField(default='Auccun', max_length=100, null=True)),
                ('dt_debut', models.DateField(default=datetime.date.today, null=True, verbose_name='Date_debut')),
                ('dt_fin', models.DateField(default=datetime.date.today, null=True, verbose_name='Date_fin')),
                ('autre_cond', models.CharField(default='Auccun', max_length=10, null=True)),
                ('nom_autre', models.CharField(default='Auccun', max_length=100, null=True)),
                ('email_autre', models.EmailField(default='', max_length=254, null=True)),
                ('cin_autre', models.PositiveIntegerField(default=0, null=True)),
                ('permis_autre', models.CharField(default='Auccun', max_length=13, null=True)),
                ('adresse_autre', models.CharField(default='Auccun', max_length=100, null=True)),
                ('nom_Client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nom_Client', to='users.profile')),
            ],
        ),
    ]
