# Generated by Django 3.2.8 on 2022-07-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nom_Agence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nom_Agence', to='agence.agence'),
        ),
    ]
