# Generated by Django 3.2.8 on 2022-07-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_user'),
        ('location', '0002_location_nom_agence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='nom_Client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nom_Client', to='users.profile'),
        ),
    ]
