# Generated by Django 3.2.8 on 2022-07-28 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_alter_location_nom_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='userLoueur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loueur', to=settings.AUTH_USER_MODEL),
        ),
    ]
