# Generated by Django 3.2.8 on 2022-07-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_table'),
        ('location', '0006_auto_20220729_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='nom_Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nom_Client', to='users.profile'),
        ),
    ]
