# Generated by Django 3.2.8 on 2022-07-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_alter_location_userloueur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='userLoueur',
            new_name='loueur',
        ),
    ]
