# Generated by Django 3.2.8 on 2022-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_rename_userloueur_location_loueur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email_autre',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
