# Generated by Django 3.2.8 on 2022-09-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_location_email_autre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='dt_debut',
        ),
        migrations.RemoveField(
            model_name='location',
            name='dt_fin',
        ),
        migrations.RemoveField(
            model_name='location',
            name='dure',
        ),
    ]
