# Generated by Django 3.2.8 on 2022-09-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0009_alter_agence_username'),
        ('location', '0018_auto_20220901_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loueur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loueur', to='agence.agence'),
        ),
    ]
