# Generated by Django 3.2.8 on 2022-09-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_loueur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loueur',
            new_name='loueur_Agence',
        ),
    ]
