# Generated by Django 3.2.8 on 2022-09-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_rename_loueur_location_loueur_agence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loueur_Agence',
            new_name='loueur',
        ),
    ]
