# Generated by Django 3.2.8 on 2022-09-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0027_alter_location_loueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='dt_debut',
        ),
        migrations.RemoveField(
            model_name='location',
            name='dt_fin',
        ),
        migrations.RemoveField(
            model_name='location',
            name='dure',
        ),
    ]
