# Generated by Django 3.2.8 on 2022-09-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_cin_profile_cins'),
        ('location', '0030_alter_location_loueur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loueur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loueur', to='users.profile'),
        ),
    ]
