# Generated by Django 3.2.8 on 2022-09-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0033_auto_20220911_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='location',
            name='num_Imat',
        ),
    ]
