# Generated by Django 3.2.8 on 2022-07-17 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cd_poste',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cin',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_nais',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nation',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_permis',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
