# Generated by Django 3.2.8 on 2022-07-18 07:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20220717_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Client',
        ),
    ]
