# Generated by Django 3.2.8 on 2022-07-18 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_rename_profile_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Profile',
        ),
    ]
