# Generated by Django 3.2.8 on 2022-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_permis',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
