# Generated by Django 3.2.8 on 2022-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220718_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_permis',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
