# Generated by Django 3.2.8 on 2022-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
