# Generated by Django 3.2.8 on 2022-07-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_cin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='client',
        ),
    ]
