# Generated by Django 3.2.8 on 2022-08-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prenom',
        ),
    ]
