# Generated by Django 3.2.8 on 2022-08-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cin',
            new_name='CIN',
        ),
    ]
