# Generated by Django 3.2.8 on 2022-08-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_cin_profile_cin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='CIN',
            new_name='cin',
        ),
    ]
