# Generated by Django 3.2.8 on 2022-08-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_cin_profile_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cin',
        ),
    ]
