# Generated by Django 3.2.8 on 2022-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cin',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
