# Generated by Django 4.1.6 on 2023-05-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Vehicule',
        ),
    ]
