# Generated by Django 4.1.6 on 2023-05-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_rename_image_vehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='image',
            new_name='photos',
        ),
    ]
