# Generated by Django 3.2.8 on 2022-08-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_form1_form2_form3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form1',
            old_name='nom',
            new_name='nomclient1',
        ),
        migrations.RenameField(
            model_name='form2',
            old_name='nom',
            new_name='nomclient2',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='nom',
            new_name='nomclient3',
        ),
    ]
