# Generated by Django 3.2.8 on 2022-09-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_cin_profile_cins'),
        ('teste', '0008_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='userProf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprof', to='users.profile'),
        ),
    ]
