# Generated by Django 4.1.6 on 2023-04-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0009_employee_userprof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
