# Generated by Django 3.2.8 on 2022-07-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_nom_client'),
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='nom_client',
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_loc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_loc', to='location.location'),
        ),
    ]
