# Generated by Django 3.2.8 on 2022-08-03 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_auto_20220720_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 11, 59, 1, 159732)),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montants',
            field=models.FloatField(),
        ),
    ]
