# Generated by Django 3.2.8 on 2022-08-03 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_table'),
        ('paiement', '0003_auto_20220803_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='loueurUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userloueur', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 13, 18, 33, 84166)),
        ),
    ]
