# Generated by Django 3.2.8 on 2022-08-07 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0006_auto_20220804_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 9, 10, 13, 305923)),
        ),
    ]
