# Generated by Django 3.2.8 on 2022-09-13 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0071_alter_paiement_date_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='num_compte',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 14, 53, 5, 243336)),
        ),
    ]
