# Generated by Django 3.2.8 on 2022-09-28 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0082_alter_paiement_date_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='num_compte',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 11, 25, 59, 994053)),
        ),
    ]
