# Generated by Django 3.2.8 on 2022-09-28 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0083_auto_20220928_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_pay',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 11, 33, 17, 501851)),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='num_compte',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
