# Generated by Django 3.2.8 on 2022-07-18 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agence', '0001_initial'),
        ('users', '0009_auto_20220718_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSerie', models.IntegerField(default=0, null=True)),
                ('numImm', models.CharField(default='', max_length=10, null=True)),
                ('dateMiseEnCirc', models.DateField(default=datetime.date.today, null=True, verbose_name='Date')),
                ('kilometrage', models.CharField(default='', max_length=10, null=True)),
                ('datePriseKm', models.DateField(default=datetime.date.today, null=True, verbose_name='Date')),
                ('type_vehicule', models.CharField(default='', max_length=50, null=True)),
                ('kilometre', models.CharField(default='', max_length=10, null=True)),
                ('marque_vehicule', models.CharField(default='', max_length=50, null=True)),
                ('nb_vehicule', models.PositiveIntegerField(default=0, null=True)),
                ('type_prix', models.CharField(default='', max_length=50, null=True)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('nom_Agences', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomAgences', to='agence.agence')),
                ('nom_Clients', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomClients', to='users.profile')),
            ],
        ),
    ]
