# Generated by Django 3.2.8 on 2022-07-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_nom_client'),
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='nom_Agences',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='nom_Clients',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='id_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_location', to='location.location'),
        ),
    ]
