# Generated by Django 3.2.8 on 2022-08-02 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_table'),
        ('voiture', '0002_auto_20220722_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='client_loueur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_loueur', to='users.profile'),
        ),
    ]
