# Generated by Django 3.2.8 on 2022-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0003_vehicule_client_loueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='datePriseKm',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='id_location',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='kilometre',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='nb_vehicule',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='numSerie',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='vehicule_photo'),
        ),
    ]
