# Generated by Django 3.2.8 on 2022-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0004_auto_20220824_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='condition',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
