# Generated by Django 3.2.8 on 2022-08-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0005_vehicule_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='numSerie',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
