# Generated by Django 3.2.8 on 2022-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0006_vehicule_numserie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='montant',
            new_name='prixJ',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='prixKm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
