# Generated by Django 3.2.8 on 2022-08-26 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0007_auto_20220824_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='date_reservetion',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='dt_debut',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='dt_fin',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='jours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='montant_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
