# Generated by Django 3.2.8 on 2022-08-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0008_auto_20220826_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='numSerie',
            field=models.IntegerField(null=True),
        ),
    ]
