# Generated by Django 3.2.8 on 2022-09-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0010_alter_vehicule_numserie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='prixKm',
        ),
    ]
