# Generated by Django 3.2.8 on 2022-09-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0012_auto_20220914_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='numImm',
            new_name='id',
        ),
    ]
