# Generated by Django 3.2.8 on 2022-09-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0013_rename_numimm_vehicule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='numImm',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
