# Generated by Django 4.1.6 on 2023-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0016_remove_vehicule_client_acheteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='images',
            field=models.ImageField(upload_to='pht_vehicule/%y'),
        ),
    ]
