# Generated by Django 4.1.6 on 2023-04-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0017_alter_vehicule_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='images',
            new_name='image',
        ),
    ]
