# Generated by Django 4.1.6 on 2023-04-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0019_rename_image_vehicule_photo_vehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='photo_vehicule',
            new_name='images',
        ),
    ]
