# Generated by Django 4.1.6 on 2023-05-02 22:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_cin_profile_cins'),
        ('voiture', '0022_rename_photo_voiture_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='caption',
        ),
        migrations.AddField(
            model_name='voiture',
            name='client_loueur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_loueur', to='users.profile'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='condition',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='dateMiseEnCirc',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='date_reservetion',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='dt_debut',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='dt_fin',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='jours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiture',
            name='kilometrage',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='marque_vehicule',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='montant_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiture',
            name='numImm',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='numSerie',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='prixJ',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiture',
            name='type_prix',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='type_vehicule',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
