# Generated by Django 3.2.8 on 2022-07-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agence', '0002_agence_useragence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='userAgence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loueurAgence', to=settings.AUTH_USER_MODEL),
        ),
    ]
