# Generated by Django 3.2.8 on 2022-07-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_table'),
        ('agence', '0005_alter_agence_useragence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='userAgence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loueurAgence', to='users.profile'),
        ),
    ]
