# Generated by Django 3.2.8 on 2022-09-04 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agence', '0008_alter_agence_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenceloueur', to=settings.AUTH_USER_MODEL),
        ),
    ]
