# Generated by Django 3.2.8 on 2022-09-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_cin_profile_cins'),
        ('agence', '0016_alter_agence_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='username',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loueurAgence', to='users.profile'),
        ),
    ]
