# Generated by Django 3.2.8 on 2022-09-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0011_remove_vehicule_prixkm'),
        ('agence', '0018_alter_agence_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicu_Agence', to='voiture.vehicule'),
        ),
    ]
