# Generated by Django 3.2.8 on 2022-09-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0019_agence_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='vehicule',
        ),
    ]
