# Generated by Django 3.2.8 on 2022-09-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0020_remove_agence_vehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agence',
            old_name='username',
            new_name='userLoueur',
        ),
    ]
